#Kotlin
kotlin.code.style=official
kotlin.daemon.jvmargs=-Xmx3072M
konan.ignoreXcodeVersion=true

#Gradle
org.gradle.jvmargs=-Xmx4096M -Dfile.encoding=UTF-8
org.gradle.configuration-cache=false
org.gradle.caching=true

#Android
org.gradle.java.home=/Applications/Android Studio.app/Contents/jbr/Contents/Home
android.nonTransitiveRClass=true
android.useAndroidX=true
android.overridePathCheck=true
android.builtInKotlin=true
android.newDsl=true

#kotlin.native.cacheKind=none
